Enhance Code Quality: Integrate isort, Update uWSGI Version, and refine pylint configuration paths(#4566)
* Add isort

* Add installation for isort

* Add files after running isort

* Add files after running isort

* Minor fix

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -50,10 +50,12 @@ jobs:
 
         # Check Code Quality
         - docker-compose run -e DJANGO_SETTINGS_MODULE=settings.dev -e VERBOSE=1 django bash -c "
-          echo 'Installing black, flake8, and pylint...' &&
-          pip install black==24.8.0 flake8==3.8.2 pylint==3.3.6 &&
+          echo 'Installing black, flake8, pylint and isort...' &&
+          pip install black==24.8.0 flake8==3.8.2 pylint==3.3.6 isort==5.12.0 &&
           echo 'Running black check...' &&
           black --check --diff ./ || { echo 'Black check failed!'; travis_terminate 1; } &&
+          echo 'Running isort check...' &&
+          isort --check-only --diff --profile=black ./ || { echo 'isort check failed!'; travis_terminate 1; } &&
           echo 'Running flake8 check...' &&
           flake8 --config=.flake8 ./ || { echo 'Flake8 check failed!'; travis_terminate 1; } &&
           echo 'Running pylint check...' &&
